-- ============================================================
-- Hosted owner provisioning — NOT a migration.
-- ============================================================
--
-- This file lives outside supabase/migrations/** on purpose. It is never
-- sent by `supabase db push`, never applied automatically, and never runs
-- as part of any local or CI workflow. It is a one-time, hand-run script.
--
-- ------------------------------------------------------------
-- HOW TO USE IT
-- ------------------------------------------------------------
--
--   1. Public signup stays disabled on the hosted project. Create the one
--      user by hand:  Dashboard > Authentication > Users > Add user
--      (set a password, and tick "Auto Confirm User").
--
--   2. Open  Dashboard > SQL Editor  and paste this whole file in.
--
--   3. Edit ONLY the two values in the "SUPPLY THESE" block below —
--      in the SQL Editor, not in this file. They are your real email and
--      your IANA timezone, and neither belongs in version control, so the
--      checked-in copy keeps its REPLACE_ME_* placeholders.
--
--      The guards below reject those placeholders on their *values* (an
--      email must contain '@'; a timezone must exist in
--      pg_catalog.pg_timezone_names) rather than by comparing against the
--      placeholder text. That way an accidental paste-and-run of the
--      unedited file fails loudly, and so does a careless find/replace
--      that also rewrites the guard.
--
--   4. Run it. It reports the row counts it ended up with.
--
-- Deliberately no psql `\set` / `:variable` syntax anywhere: the Dashboard
-- SQL Editor is not psql and does not interpret those. Everything is plain
-- SQL in a DO block, so the same text runs unchanged in the Dashboard, in
-- `supabase db query`, or in psql.
--
-- ------------------------------------------------------------
-- WHAT IT DOES
-- ------------------------------------------------------------
--
--   * Looks the owner up BY EMAIL. No hosted UUID is hardcoded here — the
--      hosted user's id is generated by GoTrue when you create the user in
--      step 1, and is not knowable ahead of time.
--   * Fails loudly unless exactly one auth.users row matches that email.
--   * Creates the matching public.profiles row (idempotent).
--   * Creates the 12 default categories (idempotent, matched
--      case-insensitively to agree with the categories_user_id_lower_name_key
--      unique index). Their ids come from the table's gen_random_uuid()
--      default — this script never invents category ids.
--   * Asserts the end state: exactly 1 Auth user, exactly 1 profile,
--      exactly 12 categories.
--
-- Running it a second time is a successful no-op: the profile and every
-- category already exist, nothing is inserted, and the same assertions pass.
--
-- No financial fixture data is seeded on the hosted project. supabase/seed.sql
-- is local-development-only.
-- ============================================================

do $$
declare
  -- ===== SUPPLY THESE (edit in the SQL Editor, never commit real values) =====
  v_owner_email    text := 'REPLACE_ME_OWNER_EMAIL';
  v_owner_timezone text := 'REPLACE_ME_OWNER_TIMEZONE';  -- IANA name, e.g. 'America/Toronto'
  -- ==========================================================================

  v_owner_id       uuid;
  v_match_count    int;
  v_profile_count  int;
  v_category_count int;
begin
  -- Value-based guards, so they survive a find/replace of the placeholders.
  if v_owner_email is null or position('@' in v_owner_email) = 0 then
    raise exception
      'v_owner_email (%) is not an email address. Edit the SUPPLY THESE block before running owner.sql.',
      v_owner_email;
  end if;

  if not exists (
    select 1 from pg_catalog.pg_timezone_names where name = v_owner_timezone
  ) then
    raise exception
      'v_owner_timezone (%) is not a valid IANA timezone name. Edit the SUPPLY THESE block before running owner.sql.',
      v_owner_timezone;
  end if;

  -- ----------------------------------------------------------
  -- Resolve the owner by email — exactly one match required.
  -- ----------------------------------------------------------
  select count(*) into v_match_count
  from auth.users
  where lower(email) = lower(v_owner_email);

  if v_match_count = 0 then
    raise exception
      'No auth.users row matches %. Create the user first: Dashboard > Authentication > Users > Add user.',
      v_owner_email;
  elsif v_match_count > 1 then
    raise exception
      '% auth.users rows match %. This project is single-user; refusing to guess which one is the owner.',
      v_match_count, v_owner_email;
  end if;

  select id into strict v_owner_id
  from auth.users
  where lower(email) = lower(v_owner_email);

  -- ----------------------------------------------------------
  -- profiles — 1:1 with auth.users, holds the timezone.
  -- Timezone validity is enforced by the BEFORE INSERT/UPDATE trigger
  -- against pg_catalog.pg_timezone_names, so a bad value raises here.
  -- ----------------------------------------------------------
  insert into public.profiles (id, timezone)
  values (v_owner_id, v_owner_timezone)
  on conflict (id) do nothing;

  -- ----------------------------------------------------------
  -- The 12 default categories (docs/auth-design.md §3).
  -- WHERE NOT EXISTS rather than ON CONFLICT: per-user name uniqueness is
  -- a unique EXPRESSION index on (user_id, lower(name)), and matching that
  -- explicitly is clearer than relying on index inference.
  -- ----------------------------------------------------------
  insert into public.categories (user_id, name, kind)
  select v_owner_id, d.name, d.kind::public.category_kind
  from (values
    ('Salary',         'income'),
    ('Interest',       'income'),
    ('Housing',        'expense'),
    ('Groceries',      'expense'),
    ('Dining',         'expense'),
    ('Transportation', 'expense'),
    ('Entertainment',  'expense'),
    ('Shopping',       'expense'),
    ('Utilities',      'expense'),
    ('Healthcare',     'expense'),
    ('Subscriptions',  'expense'),
    ('Insurance',      'expense')
  ) as d(name, kind)
  where not exists (
    select 1
    from public.categories existing
    where existing.user_id = v_owner_id
      and lower(existing.name) = lower(d.name)
  );

  -- ----------------------------------------------------------
  -- Assert the end state.
  -- ----------------------------------------------------------
  select count(*) into v_match_count from auth.users where id = v_owner_id;
  if v_match_count <> 1 then
    raise exception 'expected exactly 1 matching Auth user, found %', v_match_count;
  end if;

  select count(*) into v_profile_count from public.profiles where id = v_owner_id;
  if v_profile_count <> 1 then
    raise exception 'expected exactly 1 profile for the owner, found %', v_profile_count;
  end if;

  select count(*) into v_category_count from public.categories where user_id = v_owner_id;
  if v_category_count <> 12 then
    raise exception 'expected exactly 12 categories for the owner, found %', v_category_count;
  end if;

  raise notice 'Owner provisioned: 1 Auth user, % profile, % categories.',
    v_profile_count, v_category_count;
end;
$$;
