/**
 * Generates supabase/seed.sql from the existing lib/mock/** fixtures.
 *
 * The seed reproduces the current mock-backed application exactly — it
 * inserts literal, deterministic rows only. It never calls
 * generate_bill_occurrences, write_net_worth_snapshot, or
 * write_net_worth_snapshots_for_range: those Phase 4 functions are
 * proven separately, against their own dedicated pgTAP test data, not
 * against this seed.
 *
 * Regenerating this file from an unchanged lib/mock/** must produce no
 * diff — every id, timestamp, and computed value here is a pure
 * function of the fixture data, never of the current wall-clock time or
 * of randomness.
 *
 * Run: npm run seed:generate
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  mockAccounts,
  mockBills,
  mockBudgets,
  mockCategories,
  mockGoals,
  mockNetWorthHistory,
  mockTransactions,
} from "@/lib/mock";
import type { Transaction } from "@/lib/types";
import { SEED_USER_SLUG, uuidFor } from "./seed-identity";

// UUID literal followed by a trailing comment naming the fixture slug it
// came from. A SQL block comment is required here, not a "--" line
// comment: a line comment would swallow the rest of the single-line
// INSERT statement it's embedded in, silently truncating every
// statement after the first mid-line comment.
function idLit(slug: string): string {
  return `'${uuidFor(slug)}' /* ${slug} */`;
}

// ============================================================
// SQL literal helpers
// ============================================================

function str(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function dateLit(s: string): string {
  return `'${s}'::date`;
}

function tsLit(iso: string): string {
  return `'${iso}'::timestamptz`;
}

function nullable(inner: string | null): string {
  return inner === null ? "null" : inner;
}

// ============================================================
// Fixed local user — placeholder only. No password, no auth.identities,
// no login internals. Exists solely so profiles.id has a satisfiable
// auth.users(id) FK for local seed/pgTAP ownership testing.
//
// The insert carries ON CONFLICT (id) DO NOTHING because two workflows
// apply this seed against the same fixed id:
//
//   npm run db:reset          no auth.users row exists yet, so this
//                             placeholder is inserted as before — still
//                             not login-capable.
//   npm run auth:reset-local  scripts/provision-owner.ts has already
//                             created a REAL, login-capable GoTrue user
//                             at this id through the Auth Admin API. The
//                             conflict clause preserves that user — its
//                             password, its auth.identities row, all of
//                             its GoTrue internals — and the rest of the
//                             seed simply attaches the fixture data to it.
//
// A plain insert would abort the second workflow; an ON CONFLICT DO
// UPDATE would corrupt a real user. Never add instance_id,
// encrypted_password, token columns, or an auth.identities row here —
// creating a login-capable user is the Auth Admin API's job, not this
// generator's.
// ============================================================

const USER_SLUG = SEED_USER_SLUG;
const USER_ID = uuidFor(USER_SLUG);

const lines: string[] = [];
function emit(line: string) {
  lines.push(line);
}

emit("-- Generated by scripts/generate-seed.ts from lib/mock/**. Do not hand-edit.");
emit("-- Regenerate with: npm run seed:generate");
emit("-- LOCAL DEVELOPMENT ONLY — never sent by `supabase db push` (migrations only).");
emit("");
emit("begin;");
emit("");

// ============================================================
// auth.users + profiles — one fixed placeholder user
// ============================================================

emit("-- Placeholder local user (no password, no auth.identities row — not login-capable).");
emit("-- Left untouched when a real owner already exists at this id (npm run auth:reset-local).");
emit(
  `insert into auth.users (id, aud, role, email) values (${idLit(USER_SLUG)}, 'authenticated', 'authenticated', 'seed-user@local.test') on conflict (id) do nothing;`
);
emit(`insert into public.profiles (id, timezone) values (${idLit(USER_SLUG)}, 'UTC');`);
emit("");

// ============================================================
// categories — the default set, per docs/auth-design.md §3
// ============================================================

emit("-- categories");
for (const c of mockCategories) {
  emit(
    `insert into public.categories (id, user_id, name, kind) values (${idLit(c.id)}, '${USER_ID}', ${str(c.name)}, ${str(c.kind)});`
  );
}
emit("");

// ============================================================
// accounts — opening_balance_cents back-computed from fixture balance
// minus the sum of that account's seeded transactions
// ============================================================

const txnSumByAccount = new Map<string, number>();
for (const t of mockTransactions) {
  txnSumByAccount.set(t.accountId, (txnSumByAccount.get(t.accountId) ?? 0) + t.amountCents);
}

emit("-- accounts (opening_balance_cents = fixture balanceCents - SUM(seeded transactions))");
for (const a of mockAccounts) {
  const openingBalance = a.balanceCents - (txnSumByAccount.get(a.id) ?? 0);
  const creditLimit = a.creditLimitCents !== undefined ? String(a.creditLimitCents) : "null";
  const interestRate = a.interestRateBps !== undefined ? String(a.interestRateBps) : "null";
  emit(
    `insert into public.accounts (id, user_id, name, institution, type, opening_balance_cents, credit_limit_cents, interest_rate_bps, is_archived) values (${idLit(a.id)}, '${USER_ID}', ${str(a.name)}, ${str(a.institution)}, ${str(a.type)}, ${openingBalance}, ${creditLimit}, ${interestRate}, ${a.isArchived});`
  );
}
emit("");

// ============================================================
// movements + transactions
// ============================================================

const movementSlugs: string[] = [];
const seenMovements = new Set<string>();
for (const t of mockTransactions) {
  if (t.movementId && !seenMovements.has(t.movementId)) {
    seenMovements.add(t.movementId);
    movementSlugs.push(t.movementId);
  }
}
const movementKindBySlug = new Map<string, string>();
for (const t of mockTransactions) {
  if (t.movementId) movementKindBySlug.set(t.movementId, t.kind);
}

emit("-- movements (parents of the transfer/credit_card_payment leg pairs)");
for (const slug of movementSlugs) {
  emit(
    `insert into public.movements (id, user_id, kind) values (${idLit(slug)}, '${USER_ID}', ${str(movementKindBySlug.get(slug)!)});`
  );
}
emit("");

// created_at: deterministic from fixture array order — reproduces the
// same date DESC, created_at DESC, id ASC ordering as
// lib/data/transactions.ts's fixture-index sort.
const CREATED_AT_BASE = Date.UTC(2026, 0, 1, 0, 0, 0);
function createdAtFor(index: number): string {
  return new Date(CREATED_AT_BASE + (index + 1) * 1000).toISOString();
}

emit("-- transactions");
mockTransactions.forEach((t: Transaction, index: number) => {
  const categoryId = t.categoryId ? idLit(t.categoryId) : "null";
  const movementId = t.movementId ? idLit(t.movementId) : "null";
  emit(
    `insert into public.transactions (id, user_id, account_id, date, merchant, kind, category_id, movement_id, amount_cents, created_at) values (${idLit(t.id)}, '${USER_ID}', ${idLit(t.accountId)}, ${dateLit(t.date)}, ${str(t.merchant)}, ${str(t.kind)}, ${categoryId}, ${movementId}, ${t.amountCents}, ${tsLit(createdAtFor(index))});`
  );
});
emit("");

// ============================================================
// budgets
// ============================================================

emit("-- budgets");
for (const b of mockBudgets) {
  emit(
    `insert into public.budgets (id, user_id, category_id, period, limit_cents) values (${idLit(b.id)}, '${USER_ID}', ${idLit(b.categoryId)}, ${str(b.period)}, ${b.limitCents});`
  );
}
emit("");

// ============================================================
// bills + literal bill_occurrences
// ============================================================
// anchor_date is back-dated so the earliest `scheduled` occurrence lands
// exactly on the fixture's current dueDate. Historical occurrences are
// literal rows (never generated by private.generate_bill_occurrences),
// linked to real transactions where the approved mapping has them.

interface OccurrenceSeed {
  dueDate: string;
  status: "scheduled" | "paid" | "skipped";
  paidOn: string | null;
  transactionSlug: string | null;
}

interface BillSeed {
  slug: string;
  anchorDate: string;
  occurrences: OccurrenceSeed[];
}

const billSeeds: BillSeed[] = [
  {
    slug: "bill-electric",
    anchorDate: "2026-03-18",
    occurrences: [
      { dueDate: "2026-03-18", status: "paid", paidOn: "2026-03-10", transactionSlug: "txn-007" },
      { dueDate: "2026-04-18", status: "paid", paidOn: "2026-04-11", transactionSlug: "txn-024" },
      { dueDate: "2026-05-18", status: "paid", paidOn: "2026-05-12", transactionSlug: "txn-042" },
      { dueDate: "2026-06-18", status: "paid", paidOn: "2026-06-11", transactionSlug: "txn-058" },
      { dueDate: "2026-07-18", status: "paid", paidOn: "2026-07-12", transactionSlug: "txn-074" },
      { dueDate: "2026-08-18", status: "scheduled", paidOn: null, transactionSlug: null },
    ],
  },
  {
    slug: "bill-streaming",
    anchorDate: "2026-03-22",
    occurrences: [
      { dueDate: "2026-03-22", status: "paid", paidOn: "2026-03-07", transactionSlug: "txn-005" },
      { dueDate: "2026-04-22", status: "paid", paidOn: "2026-04-06", transactionSlug: "txn-022" },
      { dueDate: "2026-05-22", status: "paid", paidOn: "2026-05-07", transactionSlug: "txn-039" },
      { dueDate: "2026-06-22", status: "paid", paidOn: "2026-06-07", transactionSlug: "txn-056" },
      { dueDate: "2026-07-22", status: "paid", paidOn: "2026-07-07", transactionSlug: "txn-072" },
      { dueDate: "2026-08-22", status: "scheduled", paidOn: null, transactionSlug: null },
    ],
  },
  {
    slug: "bill-internet",
    anchorDate: "2026-03-23",
    occurrences: [
      { dueDate: "2026-03-23", status: "paid", paidOn: "2026-03-23", transactionSlug: null },
      { dueDate: "2026-04-23", status: "paid", paidOn: "2026-04-23", transactionSlug: null },
      { dueDate: "2026-05-23", status: "paid", paidOn: "2026-05-23", transactionSlug: null },
      { dueDate: "2026-06-23", status: "paid", paidOn: "2026-06-23", transactionSlug: null },
      { dueDate: "2026-07-23", status: "paid", paidOn: "2026-07-23", transactionSlug: null },
      { dueDate: "2026-08-23", status: "scheduled", paidOn: null, transactionSlug: null },
    ],
  },
  {
    slug: "bill-gym",
    anchorDate: "2026-04-01",
    occurrences: [
      { dueDate: "2026-04-01", status: "paid", paidOn: "2026-04-01", transactionSlug: null },
      { dueDate: "2026-05-01", status: "paid", paidOn: "2026-05-01", transactionSlug: null },
      { dueDate: "2026-06-01", status: "paid", paidOn: "2026-06-01", transactionSlug: null },
      { dueDate: "2026-07-01", status: "paid", paidOn: "2026-07-01", transactionSlug: null },
      { dueDate: "2026-08-01", status: "skipped", paidOn: null, transactionSlug: null },
      { dueDate: "2026-09-01", status: "scheduled", paidOn: null, transactionSlug: null },
    ],
  },
  {
    slug: "bill-insurance",
    anchorDate: "2025-09-05",
    occurrences: [
      // Manually recorded payment — no linked transaction. (The
      // fixture's "State Farm Insurance" transaction on 2026-06-19 is a
      // coincidental amount match, not this bill's occurrence: the mock
      // model has never linked Bill and Transaction, and a June date
      // cannot be reached by this September-anchored yearly recurrence
      // without breaking the September-anchored dueDate the fixture
      // shows today.)
      { dueDate: "2025-09-05", status: "paid", paidOn: "2025-09-05", transactionSlug: null },
      { dueDate: "2026-09-05", status: "scheduled", paidOn: null, transactionSlug: null },
    ],
  },
];

emit("-- bills");
for (const bill of mockBills) {
  const seed = billSeeds.find((b) => b.slug === bill.id);
  if (!seed) throw new Error(`no bill seed mapping for fixture bill ${bill.id}`);
  emit(
    `insert into public.bills (id, user_id, name, amount_cents, frequency, anchor_date, category_id, account_id, is_archived) values (${idLit(bill.id)}, '${USER_ID}', ${str(bill.name)}, ${bill.amountCents}, ${str(bill.frequency)}, ${dateLit(seed.anchorDate)}, ${bill.categoryId ? idLit(bill.categoryId) : "null"}, ${bill.accountId ? idLit(bill.accountId) : "null"}, false);`
  );
}
emit("");

emit("-- bill_occurrences (literal — never generated by private.generate_bill_occurrences)");
for (const bill of mockBills) {
  const seed = billSeeds.find((b) => b.slug === bill.id)!;
  for (const occ of seed.occurrences) {
    const occSlug = `${bill.id}-occ-${occ.dueDate}`;
    const txnId = occ.transactionSlug ? idLit(occ.transactionSlug) : "null";
    const paidOn = occ.paidOn ? dateLit(occ.paidOn) : "null";
    emit(
      `insert into public.bill_occurrences (id, user_id, bill_id, due_date, status, amount_cents, transaction_id, paid_on) values (${idLit(occSlug)}, '${USER_ID}', ${idLit(bill.id)}, ${dateLit(occ.dueDate)}, ${str(occ.status)}, ${bill.amountCents}, ${nullable(txnId)}, ${nullable(paidOn)});`
    );
  }
}
emit("");

// ============================================================
// goals + goal_contributions
// ============================================================
// Each fixture savedCents is represented by 2-3 dated contributions
// summing exactly to it. goal-home-renovation includes a negative
// correction row, exercising signed contributions.

interface ContributionSeed {
  occurredOn: string;
  amountCents: number;
  note: string | null;
}

const goalContributionSeeds: Record<string, ContributionSeed[]> = {
  "goal-emergency-fund": [
    { occurredOn: "2026-03-01", amountCents: 400000, note: null },
    { occurredOn: "2026-05-01", amountCents: 350000, note: null },
    { occurredOn: "2026-07-01", amountCents: 225000, note: null },
  ],
  "goal-europe-trip": [
    { occurredOn: "2026-03-01", amountCents: 300000, note: null },
    { occurredOn: "2026-06-01", amountCents: 200000, note: null },
  ],
  "goal-car-down-payment": [
    { occurredOn: "2026-04-01", amountCents: 150000, note: null },
    { occurredOn: "2026-07-01", amountCents: 60000, note: null },
  ],
  "goal-home-renovation": [
    { occurredOn: "2026-03-01", amountCents: 400000, note: null },
    { occurredOn: "2026-06-01", amountCents: -55000, note: "Correction" },
  ],
};

for (const [slug, contributions] of Object.entries(goalContributionSeeds)) {
  const sum = contributions.reduce((acc, c) => acc + c.amountCents, 0);
  const fixture = mockGoals.find((g) => g.id === slug);
  if (!fixture) throw new Error(`no fixture goal for seed mapping ${slug}`);
  if (sum !== fixture.savedCents) {
    throw new Error(
      `goal_contributions for ${slug} sum to ${sum}, expected fixture savedCents ${fixture.savedCents}`
    );
  }
}

emit("-- goals");
for (const g of mockGoals) {
  const targetDate = g.targetDate ? dateLit(g.targetDate) : "null";
  emit(
    `insert into public.goals (id, user_id, name, target_cents, target_date) values (${idLit(g.id)}, '${USER_ID}', ${str(g.name)}, ${g.targetCents}, ${targetDate});`
  );
}
emit("");

emit("-- goal_contributions");
for (const g of mockGoals) {
  const contributions = goalContributionSeeds[g.id] ?? [];
  contributions.forEach((c, i) => {
    const slug = `${g.id}-contribution-${i}`;
    const note = c.note ? str(c.note) : "null";
    emit(
      `insert into public.goal_contributions (id, user_id, goal_id, amount_cents, occurred_on, note) values (${idLit(slug)}, '${USER_ID}', ${idLit(g.id)}, ${c.amountCents}, ${dateLit(c.occurredOn)}, ${note});`
    );
  });
}
emit("");

// ============================================================
// net_worth_snapshots — all six fixture rows, verbatim.
// D9 rejected: NOT regenerated from the ledger. The snapshot writer is
// tested against its own dedicated pgTAP data, never against this seed.
// ============================================================

emit("-- net_worth_snapshots (verbatim from lib/mock/net-worth.ts — never derived here)");
for (const s of mockNetWorthHistory) {
  emit(
    `insert into public.net_worth_snapshots (user_id, month, assets_cents, liabilities_cents, net_worth_cents) values ('${USER_ID}', ${str(s.month)}, ${s.assetsCents}, ${s.liabilitiesCents}, ${s.netWorthCents});`
  );
}
emit("");

emit("commit;");
emit("");

const outPath = resolve(import.meta.dirname, "..", "supabase", "seed.sql");
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Wrote ${outPath}`);
